version: "3.8"

services:
  imgproxy:
    image: darthsim/imgproxy:latest
    ports:
      - "8080:8080"
    env_file:
      - .env # This loads all variables from the .env file
    environment:
      - IMGPROXY_KEY=${IMGPROXY_KEY}
      - IMGPROXY_SALT=${IMGPROXY_SALT}
      - IMGPROXY_ALLOW_ORIGIN=${IMGPROXY_ALLOW_ORIGIN}
      - IMGPROXY_ENABLE_WEBP_DETECTION=${IMGPROXY_ENABLE_WEBP_DETECTION}
      - IMGPROXY_SIGNATURE_SIZE=${IMGPROXY_SIGNATURE_SIZE}
      - IMGPROXY_ENABLE_AVIF_DETECTION=${IMGPROXY_ENABLE_AVIF_DETECTION}
      - IMGPROXY_USE_ETAG=${IMGPROXY_USE_ETAG}
      - IMGPROXY_LOG_LEVEL=${IMGPROXY_LOG_LEVEL}
      - IMGPROXY_AUTO_WEBP=${IMGPROXY_AUTO_WEBP}
      - IMGPROXY_AUTO_AVIF=${IMGPROXY_AUTO_AVIF}
